version: '3.7'
services:
  auth_service:
    build:
      dockerfile: Dockerfile.auth_service
      context: .
      args:
        - APP_PKG_NAME=b2b/m
        - GOOS=linux
    ports:
      - "10123:10123"
      - "11123:8080"
    environment:
      - USER_DB_URL=postgres://b2b:b2b@host.docker.internal:5432/b2b
      - USER_GRPC_PORT=10123 
      - USER_PREFIX_LEN=3

  gateway:
    depends_on:
      - auth_service
    build:
      dockerfile: Dockerfile.gateway
      context: .
      args:
        - APP_PKG_NAME=b2b/m
        - GOOS=linux
    ports:
      - "8080:8081"
      - "18080:8080"
    environment:
      - GATEWAY_HTTP_PORT=:8081
      - GATEWAY_AUTH_ENDPOINT=host.docker.internal:10123
      - GATEWAY_DB_URL=postgres://b2b:b2b@host.docker.internal:5432/b2b


