global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: auth_service
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.17.0.1:11123'

  - job_name: review_service
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.17.0.1:19090'

  - job_name: sight_service
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.17.0.1:11124'

  - job_name: trip_service
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.17.0.1:16666'

  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.17.0.1:8080'

  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.17.0.1:9100'

  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.17.0.1:9000'

