// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/services/auth/api_grpc.pb.go

// Package mock_auth_service is a generated GoMock package.
package mock_auth_service

import (
	auth_service "b2b/m/pkg/services/auth"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockAuthServiceClient is a mock of AuthServiceClient interface.
type MockAuthServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceClientMockRecorder
}

// MockAuthServiceClientMockRecorder is the mock recorder for MockAuthServiceClient.
type MockAuthServiceClientMockRecorder struct {
	mock *MockAuthServiceClient
}

// NewMockAuthServiceClient creates a new mock instance.
func NewMockAuthServiceClient(ctrl *gomock.Controller) *MockAuthServiceClient {
	mock := &MockAuthServiceClient{ctrl: ctrl}
	mock.recorder = &MockAuthServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceClient) EXPECT() *MockAuthServiceClientMockRecorder {
	return m.recorder
}

// AddPayment mocks base method.
func (m *MockAuthServiceClient) AddPayment(ctx context.Context, in *auth_service.AddPaymentRequest, opts ...grpc.CallOption) (*auth_service.PaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPayment", varargs...)
	ret0, _ := ret[0].(*auth_service.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPayment indicates an expected call of AddPayment.
func (mr *MockAuthServiceClientMockRecorder) AddPayment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPayment", reflect.TypeOf((*MockAuthServiceClient)(nil).AddPayment), varargs...)
}

// CheckEmail mocks base method.
func (m *MockAuthServiceClient) CheckEmail(ctx context.Context, in *auth_service.CheckEmailRequest, opts ...grpc.CallOption) (*auth_service.GetPublicUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckEmail", varargs...)
	ret0, _ := ret[0].(*auth_service.GetPublicUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEmail indicates an expected call of CheckEmail.
func (mr *MockAuthServiceClientMockRecorder) CheckEmail(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmail", reflect.TypeOf((*MockAuthServiceClient)(nil).CheckEmail), varargs...)
}

// FastRegister mocks base method.
func (m *MockAuthServiceClient) FastRegister(ctx context.Context, in *auth_service.FastRegisterRequest, opts ...grpc.CallOption) (*auth_service.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FastRegister", varargs...)
	ret0, _ := ret[0].(*auth_service.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FastRegister indicates an expected call of FastRegister.
func (mr *MockAuthServiceClientMockRecorder) FastRegister(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FastRegister", reflect.TypeOf((*MockAuthServiceClient)(nil).FastRegister), varargs...)
}

// GetCompanyUserLink mocks base method.
func (m *MockAuthServiceClient) GetCompanyUserLink(ctx context.Context, in *auth_service.UserAndCompanyIdsRequest, opts ...grpc.CallOption) (*auth_service.GetCompanyUserLinkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCompanyUserLink", varargs...)
	ret0, _ := ret[0].(*auth_service.GetCompanyUserLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyUserLink indicates an expected call of GetCompanyUserLink.
func (mr *MockAuthServiceClientMockRecorder) GetCompanyUserLink(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyUserLink", reflect.TypeOf((*MockAuthServiceClient)(nil).GetCompanyUserLink), varargs...)
}

// GetPayment mocks base method.
func (m *MockAuthServiceClient) GetPayment(ctx context.Context, in *auth_service.GetPaymentRequest, opts ...grpc.CallOption) (*auth_service.PaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPayment", varargs...)
	ret0, _ := ret[0].(*auth_service.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockAuthServiceClientMockRecorder) GetPayment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockAuthServiceClient)(nil).GetPayment), varargs...)
}

// GetUser mocks base method.
func (m *MockAuthServiceClient) GetUser(ctx context.Context, in *auth_service.GetUserRequest, opts ...grpc.CallOption) (*auth_service.GetUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUser", varargs...)
	ret0, _ := ret[0].(*auth_service.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthServiceClientMockRecorder) GetUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUser), varargs...)
}

// GetUserByEmail mocks base method.
func (m *MockAuthServiceClient) GetUserByEmail(ctx context.Context, in *auth_service.UserEmailRequest, opts ...grpc.CallOption) (*auth_service.UserId, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserByEmail", varargs...)
	ret0, _ := ret[0].(*auth_service.UserId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockAuthServiceClientMockRecorder) GetUserByEmail(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUserByEmail), varargs...)
}

// GetUserIdByCookie mocks base method.
func (m *MockAuthServiceClient) GetUserIdByCookie(ctx context.Context, in *auth_service.GetUserIdByCookieRequest, opts ...grpc.CallOption) (*auth_service.UserId, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserIdByCookie", varargs...)
	ret0, _ := ret[0].(*auth_service.UserId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdByCookie indicates an expected call of GetUserIdByCookie.
func (mr *MockAuthServiceClientMockRecorder) GetUserIdByCookie(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdByCookie", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUserIdByCookie), varargs...)
}

// GetUserInfo mocks base method.
func (m *MockAuthServiceClient) GetUserInfo(ctx context.Context, in *auth_service.GetUserRequest, opts ...grpc.CallOption) (*auth_service.UserInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInfo", varargs...)
	ret0, _ := ret[0].(*auth_service.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockAuthServiceClientMockRecorder) GetUserInfo(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUserInfo), varargs...)
}

// GetUsersCompany mocks base method.
func (m *MockAuthServiceClient) GetUsersCompany(ctx context.Context, in *auth_service.UserIdRequest, opts ...grpc.CallOption) (*auth_service.GetPrivateCompanyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUsersCompany", varargs...)
	ret0, _ := ret[0].(*auth_service.GetPrivateCompanyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersCompany indicates an expected call of GetUsersCompany.
func (mr *MockAuthServiceClientMockRecorder) GetUsersCompany(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersCompany", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUsersCompany), varargs...)
}

// GetUsersPayments mocks base method.
func (m *MockAuthServiceClient) GetUsersPayments(ctx context.Context, in *auth_service.UserIdRequest, opts ...grpc.CallOption) (*auth_service.PaymentsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUsersPayments", varargs...)
	ret0, _ := ret[0].(*auth_service.PaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersPayments indicates an expected call of GetUsersPayments.
func (mr *MockAuthServiceClientMockRecorder) GetUsersPayments(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersPayments", reflect.TypeOf((*MockAuthServiceClient)(nil).GetUsersPayments), varargs...)
}

// HandlePaidPayments mocks base method.
func (m *MockAuthServiceClient) HandlePaidPayments(ctx context.Context, in *auth_service.HandlePaidPaymentsRequest, opts ...grpc.CallOption) (*auth_service.HandlePaidPaymentsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HandlePaidPayments", varargs...)
	ret0, _ := ret[0].(*auth_service.HandlePaidPaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandlePaidPayments indicates an expected call of HandlePaidPayments.
func (mr *MockAuthServiceClientMockRecorder) HandlePaidPayments(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePaidPayments", reflect.TypeOf((*MockAuthServiceClient)(nil).HandlePaidPayments), varargs...)
}

// LoginUser mocks base method.
func (m *MockAuthServiceClient) LoginUser(ctx context.Context, in *auth_service.LoginRequest, opts ...grpc.CallOption) (*auth_service.LoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LoginUser", varargs...)
	ret0, _ := ret[0].(*auth_service.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockAuthServiceClientMockRecorder) LoginUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockAuthServiceClient)(nil).LoginUser), varargs...)
}

// LogoutUser mocks base method.
func (m *MockAuthServiceClient) LogoutUser(ctx context.Context, in *auth_service.Session, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LogoutUser", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogoutUser indicates an expected call of LogoutUser.
func (mr *MockAuthServiceClientMockRecorder) LogoutUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutUser", reflect.TypeOf((*MockAuthServiceClient)(nil).LogoutUser), varargs...)
}

// RegisterUser mocks base method.
func (m *MockAuthServiceClient) RegisterUser(ctx context.Context, in *auth_service.RegisterRequest, opts ...grpc.CallOption) (*auth_service.RegisterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterUser", varargs...)
	ret0, _ := ret[0].(*auth_service.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockAuthServiceClientMockRecorder) RegisterUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockAuthServiceClient)(nil).RegisterUser), varargs...)
}

// UpdatePayment mocks base method.
func (m *MockAuthServiceClient) UpdatePayment(ctx context.Context, in *auth_service.UpdatePaymentRequest, opts ...grpc.CallOption) (*auth_service.PaymentResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePayment", varargs...)
	ret0, _ := ret[0].(*auth_service.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePayment indicates an expected call of UpdatePayment.
func (mr *MockAuthServiceClientMockRecorder) UpdatePayment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePayment", reflect.TypeOf((*MockAuthServiceClient)(nil).UpdatePayment), varargs...)
}

// UpdateUser mocks base method.
func (m *MockAuthServiceClient) UpdateUser(ctx context.Context, in *auth_service.UpdateUserRequest, opts ...grpc.CallOption) (*auth_service.GetPublicUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUser", varargs...)
	ret0, _ := ret[0].(*auth_service.GetPublicUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAuthServiceClientMockRecorder) UpdateUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAuthServiceClient)(nil).UpdateUser), varargs...)
}

// UpdateUserBalance mocks base method.
func (m *MockAuthServiceClient) UpdateUserBalance(ctx context.Context, in *auth_service.UpdateUserBalanceRequest, opts ...grpc.CallOption) (*auth_service.GetPublicUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUserBalance", varargs...)
	ret0, _ := ret[0].(*auth_service.GetPublicUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserBalance indicates an expected call of UpdateUserBalance.
func (mr *MockAuthServiceClientMockRecorder) UpdateUserBalance(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserBalance", reflect.TypeOf((*MockAuthServiceClient)(nil).UpdateUserBalance), varargs...)
}

// ValidateSession mocks base method.
func (m *MockAuthServiceClient) ValidateSession(ctx context.Context, in *auth_service.Session, opts ...grpc.CallOption) (*auth_service.ValidateSessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ValidateSession", varargs...)
	ret0, _ := ret[0].(*auth_service.ValidateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthServiceClientMockRecorder) ValidateSession(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthServiceClient)(nil).ValidateSession), varargs...)
}

// MockAuthServiceServer is a mock of AuthServiceServer interface.
type MockAuthServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceServerMockRecorder
}

// MockAuthServiceServerMockRecorder is the mock recorder for MockAuthServiceServer.
type MockAuthServiceServerMockRecorder struct {
	mock *MockAuthServiceServer
}

// NewMockAuthServiceServer creates a new mock instance.
func NewMockAuthServiceServer(ctrl *gomock.Controller) *MockAuthServiceServer {
	mock := &MockAuthServiceServer{ctrl: ctrl}
	mock.recorder = &MockAuthServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServiceServer) EXPECT() *MockAuthServiceServerMockRecorder {
	return m.recorder
}

// AddPayment mocks base method.
func (m *MockAuthServiceServer) AddPayment(arg0 context.Context, arg1 *auth_service.AddPaymentRequest) (*auth_service.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPayment", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPayment indicates an expected call of AddPayment.
func (mr *MockAuthServiceServerMockRecorder) AddPayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPayment", reflect.TypeOf((*MockAuthServiceServer)(nil).AddPayment), arg0, arg1)
}

// CheckEmail mocks base method.
func (m *MockAuthServiceServer) CheckEmail(arg0 context.Context, arg1 *auth_service.CheckEmailRequest) (*auth_service.GetPublicUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckEmail", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.GetPublicUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckEmail indicates an expected call of CheckEmail.
func (mr *MockAuthServiceServerMockRecorder) CheckEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckEmail", reflect.TypeOf((*MockAuthServiceServer)(nil).CheckEmail), arg0, arg1)
}

// FastRegister mocks base method.
func (m *MockAuthServiceServer) FastRegister(arg0 context.Context, arg1 *auth_service.FastRegisterRequest) (*auth_service.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FastRegister", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FastRegister indicates an expected call of FastRegister.
func (mr *MockAuthServiceServerMockRecorder) FastRegister(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FastRegister", reflect.TypeOf((*MockAuthServiceServer)(nil).FastRegister), arg0, arg1)
}

// GetCompanyUserLink mocks base method.
func (m *MockAuthServiceServer) GetCompanyUserLink(arg0 context.Context, arg1 *auth_service.UserAndCompanyIdsRequest) (*auth_service.GetCompanyUserLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyUserLink", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.GetCompanyUserLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyUserLink indicates an expected call of GetCompanyUserLink.
func (mr *MockAuthServiceServerMockRecorder) GetCompanyUserLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyUserLink", reflect.TypeOf((*MockAuthServiceServer)(nil).GetCompanyUserLink), arg0, arg1)
}

// GetPayment mocks base method.
func (m *MockAuthServiceServer) GetPayment(arg0 context.Context, arg1 *auth_service.GetPaymentRequest) (*auth_service.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockAuthServiceServerMockRecorder) GetPayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockAuthServiceServer)(nil).GetPayment), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockAuthServiceServer) GetUser(arg0 context.Context, arg1 *auth_service.GetUserRequest) (*auth_service.GetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthServiceServerMockRecorder) GetUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthServiceServer)(nil).GetUser), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockAuthServiceServer) GetUserByEmail(arg0 context.Context, arg1 *auth_service.UserEmailRequest) (*auth_service.UserId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.UserId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockAuthServiceServerMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockAuthServiceServer)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserIdByCookie mocks base method.
func (m *MockAuthServiceServer) GetUserIdByCookie(arg0 context.Context, arg1 *auth_service.GetUserIdByCookieRequest) (*auth_service.UserId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdByCookie", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.UserId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdByCookie indicates an expected call of GetUserIdByCookie.
func (mr *MockAuthServiceServerMockRecorder) GetUserIdByCookie(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdByCookie", reflect.TypeOf((*MockAuthServiceServer)(nil).GetUserIdByCookie), arg0, arg1)
}

// GetUserInfo mocks base method.
func (m *MockAuthServiceServer) GetUserInfo(arg0 context.Context, arg1 *auth_service.GetUserRequest) (*auth_service.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockAuthServiceServerMockRecorder) GetUserInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockAuthServiceServer)(nil).GetUserInfo), arg0, arg1)
}

// GetUsersCompany mocks base method.
func (m *MockAuthServiceServer) GetUsersCompany(arg0 context.Context, arg1 *auth_service.UserIdRequest) (*auth_service.GetPrivateCompanyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersCompany", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.GetPrivateCompanyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersCompany indicates an expected call of GetUsersCompany.
func (mr *MockAuthServiceServerMockRecorder) GetUsersCompany(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersCompany", reflect.TypeOf((*MockAuthServiceServer)(nil).GetUsersCompany), arg0, arg1)
}

// GetUsersPayments mocks base method.
func (m *MockAuthServiceServer) GetUsersPayments(arg0 context.Context, arg1 *auth_service.UserIdRequest) (*auth_service.PaymentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersPayments", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.PaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersPayments indicates an expected call of GetUsersPayments.
func (mr *MockAuthServiceServerMockRecorder) GetUsersPayments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersPayments", reflect.TypeOf((*MockAuthServiceServer)(nil).GetUsersPayments), arg0, arg1)
}

// HandlePaidPayments mocks base method.
func (m *MockAuthServiceServer) HandlePaidPayments(arg0 context.Context, arg1 *auth_service.HandlePaidPaymentsRequest) (*auth_service.HandlePaidPaymentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePaidPayments", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.HandlePaidPaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandlePaidPayments indicates an expected call of HandlePaidPayments.
func (mr *MockAuthServiceServerMockRecorder) HandlePaidPayments(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePaidPayments", reflect.TypeOf((*MockAuthServiceServer)(nil).HandlePaidPayments), arg0, arg1)
}

// LoginUser mocks base method.
func (m *MockAuthServiceServer) LoginUser(arg0 context.Context, arg1 *auth_service.LoginRequest) (*auth_service.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockAuthServiceServerMockRecorder) LoginUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockAuthServiceServer)(nil).LoginUser), arg0, arg1)
}

// LogoutUser mocks base method.
func (m *MockAuthServiceServer) LogoutUser(arg0 context.Context, arg1 *auth_service.Session) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogoutUser", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogoutUser indicates an expected call of LogoutUser.
func (mr *MockAuthServiceServerMockRecorder) LogoutUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutUser", reflect.TypeOf((*MockAuthServiceServer)(nil).LogoutUser), arg0, arg1)
}

// RegisterUser mocks base method.
func (m *MockAuthServiceServer) RegisterUser(arg0 context.Context, arg1 *auth_service.RegisterRequest) (*auth_service.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockAuthServiceServerMockRecorder) RegisterUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockAuthServiceServer)(nil).RegisterUser), arg0, arg1)
}

// UpdatePayment mocks base method.
func (m *MockAuthServiceServer) UpdatePayment(arg0 context.Context, arg1 *auth_service.UpdatePaymentRequest) (*auth_service.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePayment", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePayment indicates an expected call of UpdatePayment.
func (mr *MockAuthServiceServerMockRecorder) UpdatePayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePayment", reflect.TypeOf((*MockAuthServiceServer)(nil).UpdatePayment), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockAuthServiceServer) UpdateUser(arg0 context.Context, arg1 *auth_service.UpdateUserRequest) (*auth_service.GetPublicUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.GetPublicUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAuthServiceServerMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAuthServiceServer)(nil).UpdateUser), arg0, arg1)
}

// UpdateUserBalance mocks base method.
func (m *MockAuthServiceServer) UpdateUserBalance(arg0 context.Context, arg1 *auth_service.UpdateUserBalanceRequest) (*auth_service.GetPublicUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserBalance", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.GetPublicUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserBalance indicates an expected call of UpdateUserBalance.
func (mr *MockAuthServiceServerMockRecorder) UpdateUserBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserBalance", reflect.TypeOf((*MockAuthServiceServer)(nil).UpdateUserBalance), arg0, arg1)
}

// ValidateSession mocks base method.
func (m *MockAuthServiceServer) ValidateSession(arg0 context.Context, arg1 *auth_service.Session) (*auth_service.ValidateSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", arg0, arg1)
	ret0, _ := ret[0].(*auth_service.ValidateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockAuthServiceServerMockRecorder) ValidateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockAuthServiceServer)(nil).ValidateSession), arg0, arg1)
}

// mustEmbedUnimplementedAuthServiceServer mocks base method.
func (m *MockAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthServiceServer")
}

// mustEmbedUnimplementedAuthServiceServer indicates an expected call of mustEmbedUnimplementedAuthServiceServer.
func (mr *MockAuthServiceServerMockRecorder) mustEmbedUnimplementedAuthServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthServiceServer", reflect.TypeOf((*MockAuthServiceServer)(nil).mustEmbedUnimplementedAuthServiceServer))
}

// MockUnsafeAuthServiceServer is a mock of UnsafeAuthServiceServer interface.
type MockUnsafeAuthServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeAuthServiceServerMockRecorder
}

// MockUnsafeAuthServiceServerMockRecorder is the mock recorder for MockUnsafeAuthServiceServer.
type MockUnsafeAuthServiceServerMockRecorder struct {
	mock *MockUnsafeAuthServiceServer
}

// NewMockUnsafeAuthServiceServer creates a new mock instance.
func NewMockUnsafeAuthServiceServer(ctrl *gomock.Controller) *MockUnsafeAuthServiceServer {
	mock := &MockUnsafeAuthServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeAuthServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeAuthServiceServer) EXPECT() *MockUnsafeAuthServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedAuthServiceServer mocks base method.
func (m *MockUnsafeAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthServiceServer")
}

// mustEmbedUnimplementedAuthServiceServer indicates an expected call of mustEmbedUnimplementedAuthServiceServer.
func (mr *MockUnsafeAuthServiceServerMockRecorder) mustEmbedUnimplementedAuthServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthServiceServer", reflect.TypeOf((*MockUnsafeAuthServiceServer)(nil).mustEmbedUnimplementedAuthServiceServer))
}
