package constants

const MinPasswordLength = "8"
const MaxPasswordLength = "254"
const MaxEmailLength = "256"

const MinCategoryLength = "3"
const MaxCategoryLength = "128"
const MinProductNameLength = "3"
const MaxProductNameLength = "256"
const MinOrderTextLength = "3"
const MaxOrderTextLength = "1000"
const MinOrderCommentsLength = "3"
const MaxOrderCommentsLength = "1000"
const MinPhoneLength = "11"
const MaxPhoneLength = "13"
const MinCompanyNameLength = "3"
const MaxCompanyNameLength = "128"
const MinItnLength = "10"
const MaxItnLength = "12"
const MinFioLength = "6"
const MaxFioLength = "768"
