name: GitHub Actions b2b backend
run-name: ${{ github.actor }} Deploy 🚀
on:
  push:
    branches:
      - main

jobs:
  stop:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: SSH Setup
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            port: 22
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: Change user to postgres
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/change_user_cd_wd.sh
      - name: Stop docker
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/stop.sh
      - name: Exit to root 
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/exit.sh
      - name: Clean and rights
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/clean_and_rights.sh

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
        shell: bash
    needs: stop
    steps:
      - name: SSH Setup
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            port: 22
      - name: Change user to postgres
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/change_user_cd_wd.sh
      - name: Build
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/build.sh

  start:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: [build, stop]
    steps:
      - name: SSH Setup
        uses: appleboy/ssh-action@master
        with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            port: 22
      - name: Change user to postgres
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/change_user_cd_wd.sh
      - name: Start
        run: /var/lib/postgresql/backend/b2b-backend/.github/workflows/scripts/start.sh

  notify:
    if: always()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: [stop, build, start]  
    steps:
      - name: Notify Telegram on success
        if: success()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage" \
            -d chat_id="${{secrets.CHAT_ID}}" \
            -d text="[Backend] [${{github.actor}}]%0A===Successfully Deploy===%0Ahttps://bi-tu-bi.ru/%0A${{ github.event.head_commit.message }}"

      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage" \
            -d chat_id="${{secrets.CHAT_ID }}" \
            -d text="[Backend] [${{github.actor}}]%0A=!=Deployment Failed=!=%0Ahttps://bi-tu-bi.ru/%0A${{ github.event.head_commit.message }}"
